apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      volumes:
        - name: content
          configMap:
            name: kargo-demo-content
      containers:
        - name: nginx 
          image: nginx:latest
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
              readOnly: true
          resources:
            limits:
              cpu: 550m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi